# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: 5432

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>

test:
  <<: *default
  database: inventory_service_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB") %>
  cache:
    <<: *primary_production
    database: INVENTORY_SERVICE_PRODUCTION_CACHE_NAME
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: INVENTORY_SERVICE_PRODUCTION_QUEUE_NAME
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: INVENTORY_SERVICE_PRODUCTION_CABLE_NAME
    migrations_paths: db/cable_migrate
